### ISSUE TITLE
Project Wiki and Design Docs

### ISSUE THREAD

**Issue by siascone** [Yenleespace/bananabnb#1]
# Wiki Home Page
- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
  - [x] each wiki page is listed in bullet points
  - [x] all links route the correct page

---

# MVP List
- [x] Should have 7 MVPs.
  - [x] 3 of those are User Auth, Heroku, and Production README.
  - [x] The other 4 are from the [Approved Apps List](https://github.com/appacademy/cohort-resources/blob/master/full_stack_projects/aa_approved_full_stack_projects.md) or your PM will have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
  - [x] MVPs are listed in an ordered list
  - [x] Each MVP is broken down into bullet points

---

# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
  - [x] primary key
  - [x] not null
  - [x] unique
  - [x] indexed
  - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
  - [x] schema is written in a table format
  - [x] the table’s name are lowercased, snake_cased and `back_ticked`
  - [x] the table header column names are bolded
  - [x] columns names are lowercased and snaked_cased and `back_ticked`

---

# Sample State
- [x] State shape is flat!
- [x] State’s keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
  - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
  - [x] Top level slices
    - [x] `entities`
    - [x] `session`
    - [x] `errors` (here or in `ui`)
    - [x] `ui` (if needed)
  - [x] Should NOT have nested slices, aka `comments` inside of `posts`
   + Some info from other tables is ok, for instance:
    + the author username and imageurl for a post. basically any info that the user can’t change
    + like count and a boolean on whether the user likes the post instead of a likes slice

---

# Backend Routes
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
  + probably doesn’t need a `GET likes` api endpoint because that info comes through the post show

---

# Frontend Routes
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
  - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by siascone** [comment]
Notes - For all notes please reference the [BlueBird Wiki](https://github.com/appacademy/bluebird/wiki)

I love the Bananable reference in the project title!

Wiki Home Page:
- Looks great! 

MVP List:
- Add numbers to the headings so that the list presents as an ordered list (1-7)
- For Bookings and Reviews please add CRUD to the heading like so:
  - 4. Bookings - CRUD (02/07/2023, 2 days)
- Add estimated start dates to all features on the list

Database Schema:
- Looks great!
- Small typo: you are missing one backtick under the reservation bullets for listing_id

**Comment by Yenleespace** [comment]
MVP
   + Add numbers to the headings so that the list presents as an ordered list (1-7) - DONE
   + For Bookings and Reviews please add CRUD to the heading like so: - DONE
   + Bookings - CRUD (02/07/2023, 2 days) - DONE
   + Add estimated start dates to all features on the list - DONE

Database Schema
   + Small typo: you are missing one backtick under the reservation bullets for listing_id - DONE

**Comment by siascone** [comment]
Notes

Wiki Home Page
- Complete

MVP List 
- Complete

Schema
- Complete

Sample State
- Complete

Backend Routes
- Looking good.
- Listings will need a PATCH route to update the listing
- Add routes for reviews: `GET /api/reviews/:id` for a retrieving a review, `POST /api/reviews` for creating a review, `PATCH /api/reviews/:id` for updating a review, `DELETE /api/reviews/:id` for deleting a review

Frontend Routes
- Looking good
- add a return line to the `/signup` route so that `SessionForm` displays below it and tabbed in
- listing route is missing a `/` should be `/listings/:listingId`

**Comment by siascone** [comment]
Your docs look good. I would say they are complete. 

One thing to consider about your backend routes is the nested route for retrieving reviews. This is not entirely necessary. 
- Your reviews can have their own set of routes without a listing_id
- To get a list of reviews for a specific listing you can have the 'GET /api/listing/:id` return the associated data in it's show.json.jbuilder view by setting up a json key and calling the model association `json.reviews @listing.reviews` 

Let me know if you have any questions when you get to this.
